### ISSUE TITLE
Doesn't work if VS2015 is not installed

### ISSUE THREAD

**Issue by barsv** [MRCollective/TortoiseGitToolbar#11]
I have VS2013 on a fresh Windows 10. Just installed it a few days ago. I haven't installed VS2015 yet. i installed the extension. it installs fine. but when i try to press a button on the toolbar it shows an error message: 

> The 'TrotoiseGitToolbarPackage' package didn't load correctly. The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\Stan\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml'. Restarting Visual Studio could help resolve this issue.
>Continues to show this error message?
> <Yes button> <No button>

and in the ActivityLog.xml:

`<entry>`
`    <record>1027</record>`
`    <time>2016/02/24 16:37:08.436</time>`
`    <type>Information</type>`
`    <source>VisualStudio</source>`
`    <description>Begin package load [TortoiseGitToolbarPackage]</description>`
`    <guid>{F388EE16-EEF2-4AE1-85BD-4CB19151BEB0}</guid>`
`  </entry>`
`  <entry>`
`    <record>1028</record>`
`    <time>2016/02/24 16:37:08.437</time>`
`    <type>Error</type>`
`    <source>VisualStudio</source>`
`    <description>CreateInstance failed for package [TortoiseGitToolbarPackage]</description>`
`    <guid>{F388EE16-EEF2-4AE1-85BD-4CB19151BEB0}</guid>`
`    <hr>80070002</hr>`
`    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>`
`  </entry>`
`  <entry>`
`    <record>1029</record>`
`    <time>2016/02/24 16:37:08.437</time>`
`    <type>Error</type>`
`    <source>VisualStudio</source>`
`    <description>End package load [TortoiseGitToolbarPackage]</description>`
`    <guid>{F388EE16-EEF2-4AE1-85BD-4CB19151BEB0}</guid>`
`    <hr>80004005 - E_FAIL</hr>`
`    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>`
`  </entry>`

i tried to install the vsix file that i downloaded on 11-May-2015 and it works fine.
i tried to reinstall the current vsix file (downloaded today) - reproduced the error.
uninstalled it and installed again using the old vsis - works fine.

i tried to just change manifest file as it's suggested for a similar issue here: https://github.com/VioletGiraffe/cppcheck-vs-addin/issues/142 - doesn't help.

i suspect that this changeset introduced the issue: https://github.com/MRCollective/TortoiseGitToolbar/commit/af44e5f7b61a862ceb6e97209ca56a349479b8b7
but i don't know yet how to fix it to make it work on both 2015 and 2013 without 2015.

**Comment by barsv** [comment]
maybe it's not af44e5f. can it be the change of the nuget references?

maybe i'll try to find it out on the weekend by just reverting to previous revs

**Comment by MattDavies** [comment]
Hey @barsv, agree that it might have been the nuget references change. I'll do some digging as well today and at least revert the commit causing the hassle.

**Comment by MattDavies** [comment]
@barsv, sorry to take so long to get around to this.

Try grabbing 0.995 from the extension gallery and see if that resolves the issue for you.

**Comment by barsv** [comment]
@MattDavies works perfect, you are the best!
I tried in on both machines - one has only vs2013, another one has vs2013 and vs2015. it works on both. unfortunately i don't have a machine with only vs2015 to check this case also.
