### ISSUE TITLE
VS2022 support ?

### ISSUE THREAD

**Issue by jogibear9988** [MRCollective/TortoiseGitToolbar#26]
Any plans for VS2022?

**Comment by MattDavies** [comment]
Hey @jogibear9988, VS2022 is still in preview I believe.

Upgrade notes: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

Pull requests welcome if someone gets to it before I do.

**Comment by gizmocuz** [comment]
Hope you find some time Matt, I quickly tried it but had to update quite a few dependencies and the end result was that I could not make it working....

**Comment by xhafan** [comment]
I really miss my Visual Studio 2022 TortoiseGit extension's `Log`, `File Log`, `File Blame` and `File Diff` toolbar buttons. Cannot live without them :smile:

**Comment by MattDavies** [comment]
Been a little busy sorry! I'm planning to pick this up in the next couple of weeks 🥳

**Comment by denisglu** [comment]
Matt, did you have any chance? Missing this ultra useful tool very much :)

**Comment by MattDavies** [comment]
Thanks for the reminder @denisglu, I guess I lost track of this 😅

Taking a stab at this one, builds and runs tests okay locally. I'll do some testing on the generated VSIX files tomorrow.

Work in progress: https://github.com/MRCollective/TortoiseGitToolbar/pull/27

**Comment by MattDavies** [comment]
All done now, should be live in an hour or two.

**Comment by denisglu** [comment]
Thanks a lot, Matt!
