### ISSUE TITLE
Create Branch

### ISSUE THREAD

**Issue by tburnett80** [MRCollective/TortoiseGitToolbar#3]
The branch switcher is great, but I still have to go back to the explorer integration to create branches because there is no extension for the "Create Branch" option in the toolbar that results in creating remote branches or has the "Track" option. 

Id like to see a button added that is "Create Branch"

**Comment by Jason525** [comment]
Is there anyone who can solve this problem?
I think adding a "Create Branch" button is really useful. :)

**Comment by Jason525** [comment]
It's been a long time ~

**Comment by blackboxlogic** [comment]
May I recommend a work around: https://marketplace.visualstudio.com/items?itemName=NanangP.ShellContextMenu
