### ISSUE TITLE
Run commands from root of checkout

### ISSUE THREAD

**Issue by robdmoore** [MRCollective/TortoiseGitToolbar#6]
Sometimes people put `.sln` files outside of the root of the repository (e.g. in a `src` folder).

This extension runs commands from the directory of the solution, so things like logs or commit diffs only show the changes from the solution folder onwards. This means it's possible to miss changes to for example a .gitignore file and you have to go to the command line or Windows Explorer to commit the change.

It's pretty easy to find it - recurse backwards until you hit a folder that contains a `.git` directory and if you git the root of the filesystem then it's clear they don't have a git checkout.

**Comment by MattDavies** [comment]
Fixed by #13, will be released as 1.0.
