### ISSUE TITLE
Git Blame?

### ISSUE THREAD

**Issue by renatoch** [MRCollective/TortoiseGitToolbar#8]
Hey man,

First of all, great work! Helps a lot =)

I don't get Git Blame in the toolbar. 
I saw the source code and there is the command and configuration there.

Any idea why?

Thanks!

**Comment by MattDavies** [comment]
No problems, you're welcome.

I suspect I haven't actually released the version which has log/blame/diff for the current file. I'll get on to that ASAP and ping you back on here when it's out.

Thanks for the report!

**Comment by MattDavies** [comment]
I've pushed up a new release (0.96) to the VS extension gallery. Can you please check it out and let me know if you can see those commands now?

Thanks!

**Comment by renatoch** [comment]
Worked great Matt, thanks a lot! =D
